add 5-tp algorithm description
hugegraph/hugegraph-doc pull request #48
Opened 2020-04-09 15:41 UTC by zhoney

Change-Id: Ic7019dc96d8a4f9db0839d5cfa10db7596b59a6d

2020-11-02 03:53 UTC, javeme commented on clients/restful-api/traverser.md
> +    - 高级版使用POST，根据起始顶点，查找N步可达的邻居，与基础版的不同在于：
查找恰好N步可达的邻居

2020-11-02 03:53 UTC, javeme commented on clients/restful-api/traverser.md
> +    - 基础版使用GET，根据起始顶点，查找恰好N步可达的邻居
基础版使用GET方法

2020-11-02 03:53 UTC, javeme commented on clients/restful-api/traverser.md
> +    - 一种是使用GET，计算两个顶点的邻居的交并比
计算两个顶点的邻居的jaccard相似度（交并比）

2020-11-02 12:55 UTC, javeme commented on clients/restful-api/traverser.md
> +    - 高级版使用POST方法，根据一组起点和一组终点，查找两个集合间复合条件的全部路径
复合 => 符合

2020-11-02 12:55 UTC, javeme commented on clients/restful-api/traverser.md
> +- with_path：true表示返回起始点到每个邻居的最短路径，false表示不返回起始点到每个邻居的最短路径，选填项，默认为 false
"默认为 false" 统一是否需要空格

2020-11-03 04:03 UTC, javeme submitted a review, later dismissed

2020-11-03 09:59 UTC, houzhizhen approved these changes

2020-11-03 10:08 UTC, javeme submitted a review, later dismissed

2020-11-03 12:56 UTC, Linary requested changes

2020-11-03 13:14 UTC, zhoney commented on clients/restful-api/traverser.md
> +- 家族关系中，查找一个人五服以内所有子孙，person A通过连续的5条“亲子”边到达的顶点集合。
五服 就是一个词，表示亲属关系

2020-11-04 01:43 UTC, Linary submitted a review, later dismissed

2020-11-04 03:33 UTC, houzhizhen submitted a review, later dismissed

2020-11-04 05:57 UTC, javeme commented on clients/restful-api/traverser.md
> +- Single Source Shortest Path，查找一个点到其他各个点的加权最短路径
add doc for muti node shortest path

2020-11-04 05:57 UTC, javeme commented on clients/restful-api/traverser.md
> +- K-out API，根据起始顶点，查找恰好N步可达的邻居，分为基础版和高级版：
HugeGraph支持的Traverser API包括

2020-11-04 07:29 UTC, javeme approved these changes

2020-11-04 07:47 UTC, houzhizhen approved these changes

2020-11-04 07:49 UTC, merged