update tools doc for version 1.5.0
hugegraph/hugegraph-doc pull request #55
Opened 2020-11-05 12:10 UTC by zhoney

Change-Id: I1c28bc278d2cc627514f2d76bf0537630c9eb9dc

2020-11-05 12:31 UTC, houzhizhen submitted a review, later dismissed

2020-11-06 01:41 UTC, Linary requested changes

2020-11-06 01:41 UTC, Linary commented on quickstart/hugegraph-tools.md
> +./bin/hugegraph --url  http://127.0.0.1:8080  --graph hugegraph  task-list --limit 5
remove one space between 'hugegraph'  and 'task-list', ditto as follower

2020-11-06 02:43 UTC, Linary approved these changes

2020-11-06 03:35 UTC, houzhizhen approved these changes

2020-11-06 03:36 UTC, merged