add 0.11.2 release notes
hugegraph/hugegraph-doc pull request #56
Opened 2020-11-09 09:14 UTC by zhoney

Change-Id: Ie0a9037789fda4c444eaf697fb66663195a2c21a

2020-11-09 09:52 UTC, houzhizhen commented on changelog/hugegraph-0.11.2-release-notes.md
> +- 支持共同邻居，Jaccard相似度，全部最短路径，带权最短路径和单源最短路径5种遍历算法（hugegraph #936，hugegraph-client #80）
其他单词两边都有空格。Jaccard相似度没有，需要统一？

2020-11-09 09:52 UTC, houzhizhen commented on changelog/hugegraph-0.11.2-release-notes.md
> +- 修复在 studio 执行 gremlin 时的 MySQL 链接失败问题（hugegraph #765）
链->连

2020-11-09 09:52 UTC, houzhizhen commented on changelog/hugegraph-0.11.2-release-notes.md
> +- 将 Direction 和 遍历算法的类导出到 Gremlin 环境（hugegraph #904）
去掉“和”后面的空格。

2020-11-09 09:52 UTC, houzhizhen commented on changelog/hugegraph-0.11.2-release-notes.md
> +- 支持定制的 kout/kneighbor，多点最短路径，最相似 jaccard 点和模板路径5种遍历算法（hugegraph #1174，hugegraph-client #100，hugegraph-client #106）
11行Jaccard 第一个字母大写，是否需要统一？

2020-11-09 10:04 UTC, houzhizhen submitted a review, later dismissed

2020-11-09 10:19 UTC, Linary requested changes

2020-11-09 10:19 UTC, Linary commented on changelog/hugegraph-0.11.2-release-notes.md
> +- 启动HugeGraphServer 出现异常时快速失败（hugegraph #748）
启动HugeGraphServer -> 启动 HugeGraphServer

2020-11-09 10:20 UTC, Linary requested changes

2020-11-09 10:20 UTC, Linary commented on changelog/hugegraph-0.11.2-release-notes.md
> +- CSV的解析器改为 SimpleFlatMapper（hugegraph-loader #124）
add space?

2020-11-09 12:01 UTC, Linary approved these changes

2020-11-09 13:04 UTC, javeme requested changes

2020-11-09 13:04 UTC, javeme commented on changelog/hugegraph-0.11.2-release-notes.md
> +- 支持备份顶点和边时指定类型和要备份的属性信息（hugegraph-tools #63）
过滤属性信息

2020-11-09 14:46 UTC, imbajin commented on changelog/hugegraph-0.11.2-release-notes.md
> +- 修改默认日志等级为 TRACE（hugegraph #1050）
默认日志等级仍然是INFO并未修改, 是 "修改了**允许**输出的日志**最低**等级为TRACE"

2020-11-10 03:46 UTC, Linary submitted a review, later dismissed

2020-11-10 03:46 UTC, Linary commented on changelog/hugegraph-0.11.2-release-notes.md
> +- 优化顶点和边的删除效率，当提供Label+ID删除时免去查询（hugegraph #1150）
提供Label+ID删除 -> 提供 Label+ID 删除

2020-11-10 03:46 UTC, Linary commented on changelog/hugegraph-0.11.2-release-notes.md
> +- 支持导入映射文件2.0版本（hugegraph-loader #121）
add space for 2.0

2020-11-10 03:52 UTC, javeme commented on changelog/hugegraph-0.11.2-release-notes.md
> +- 支持创建 schema 时，记录创建的时间（hugegraph #746，hugegraph-client #69）
Schema

2020-11-10 03:52 UTC, javeme commented on changelog/hugegraph-0.11.2-release-notes.md
> +- 统一 RESTful API server 和 Gremlin Server 的日期格式为字符串（hugegraph #1014，hugegraph-client #82）
RESTful API Server

2020-11-10 03:52 UTC, javeme commented on changelog/hugegraph-0.11.2-release-notes.md
> +- 支持用户和细粒度权限控制（hugegraph #749，hugegraph #985，hugegraph-client #81）
支持用户认证

2020-11-10 03:52 UTC, javeme commented on changelog/hugegraph-0.11.2-release-notes.md
> +- 支持遍历顶点计数功能（hugegraph #995，hugegraph-client #84）
支持遍历 API 的顶点计数功能

2020-11-10 04:09 UTC, javeme approved these changes

2020-11-10 05:05 UTC, Linary approved these changes

2020-11-10 06:21 UTC, merged