update config-guide.md and config-option.md for relase 0.11
hugegraph/hugegraph-doc pull request #59
Opened 2020-11-10 11:28 UTC by houzhizhen

2020-11-10 11:41 UTC, javeme commented on config/config-option.md
> +edge.cache_type                  | l1                              | The type of edge cache, allowed values are [l1, l2].
move the option to the corresponding position

2020-11-11 02:54 UTC, zhoney submitted a review, later dismissed

2020-11-11 03:15 UTC, Linary requested changes

2020-11-11 03:15 UTC, Linary commented on config/config-option.md
> +vertex.part_edge_commit_size     | 5000                            | Whether to enable the mode to commit part of edges of vertex, enabled if commit size > 0, 0 meas disabled.
meas -> means

2020-11-11 03:21 UTC, Linary submitted a review, later dismissed

2020-11-11 05:18 UTC, javeme commented on config/config-option.md
> +vertex.cache_type                | l1                              | The type of vertex cache, allowed values are [l1, l2].
move to line 63

2020-11-11 05:18 UTC, javeme commented on config/config-option.md
> +edge.cache_type                  | l1                              | The type of edge cache, allowed values are [l1, l2].
ditto

2020-11-11 05:18 UTC, javeme commented on config/config-option.md
> +query.ramtable_vertices_capacity | 10000000                        | The maximum number of vertices in ramtable, generally the largest vertex id is used as capacity.
ditto

2020-11-11 05:18 UTC, javeme commented on config/config-option.md
> +
delete it

2020-11-11 06:29 UTC, javeme commented on config/config-option.md
> +oltp.concurrent_threads          | 10                              | Thread number to concurrently execute oltp algorithm.
move oltp to line 83

2020-11-11 06:29 UTC, javeme commented on config/config-option.md
> +rate_limit.write                 | 0                               | The max rate(items/s) to add/update/delete vertices/edges.
move rate_limit to line 85

2020-11-11 06:29 UTC, javeme commented on config/config-option.md
> +computer.config                  | /conf/computer.yaml             | The config file path of computer job.
move task and computer to line 85

2020-11-11 07:06 UTC, javeme approved these changes

2020-11-17 02:51 UTC, zhoney approved these changes

2020-11-17 04:11 UTC, javeme commented on config/config-guide.md
> +
remove empty line

2020-11-17 04:22 UTC, javeme approved these changes

2020-11-18 11:56 UTC, zhoney approved these changes

2020-11-18 11:58 UTC, Linary approved these changes

2020-11-18 12:27 UTC, merged