Add doc about https config and generated
hugegraph/hugegraph-doc pull request #60
Opened 2020-11-11 07:02 UTC by Linary

2020-11-11 07:15 UTC, javeme commented on config/config-https.md
> +HugeGraphServer 默认使用的是 http 协议，如果用户对请求的安全性有要求，可以配置成 https。
http => HTTP
https => HTTPS

2020-11-11 07:15 UTC, javeme commented on config/config-https.md
> +        }
catch (Exception e)

2020-11-11 07:15 UTC, javeme commented on config/config-https.md
> +```java
是否有命令行生成证书的方式呢？

2020-11-11 08:55 UTC, Linary commented on config/config-https.md
> +HugeGraphServer 默认使用的是 http 协议，如果用户对请求的安全性有要求，可以配置成 https。
config option value is https, so use https in all places

2020-11-11 09:20 UTC, javeme commented on config/config-https.md
> +    private static final String state = "beijing";
China

2020-11-11 12:09 UTC, Linary commented on config/config-https.md
> +```java
有，但是很麻烦

2020-11-12 05:38 UTC, javeme commented on config/config-https.md
> +### 客户端如何生成证书文件
”服务端生成证书文件“ 可以作为一个可选项说明下

2020-11-12 05:38 UTC, javeme commented on config/config-https.md
> +
当支持默认trustStoreFile后更新这里

2020-11-19 08:21 UTC, javeme requested changes

2020-11-19 08:21 UTC, javeme commented on config/config-https.md
> +keytool -import -alias serverkey -file server.crt -keystore client.jks
rename client.jks to client client.truststore

2020-11-19 08:21 UTC, javeme commented on config/config-https.md
> +# 执行迁移命令时，当 --target-url 中使用 https 协议时，目标 Server 所需的客户端证书文件的路径，必须显式指定
improve for default truststore file

2020-11-19 09:05 UTC, zhoney requested changes

2020-11-19 09:05 UTC, zhoney commented on config/config-https.md
> +服务端的 conf 目录下已经给出了一个的 keystore 文件`hugegraph-server.keystore`，该文件的密码为`hugegraph`，
目录下已经给出了一个的 keystore 文件
多了一个“的”

2020-11-19 09:06 UTC, houzhizhen commented on config/config-https.md
> +--protocol https
Get protocol from url?

2020-11-19 09:09 UTC, Linary commented on config/config-https.md
> +--protocol https
loader use --protocol explicitly

2020-11-19 09:11 UTC, zhoney approved these changes

2020-11-19 09:13 UTC, houzhizhen approved these changes

2020-11-19 10:02 UTC, javeme approved these changes

2020-11-19 10:02 UTC, merged