Update loader doc for release 0.11
hugegraph/hugegraph-doc pull request #62
Opened 2020-11-11 12:12 UTC by Linary

2020-11-12 04:57 UTC, javeme requested changes

2020-11-12 04:57 UTC, javeme commented on quickstart/hugegraph-loader.md
> +具体而言，每个映射块包含**一个输入源**和多个**顶点映射**和**边映射**块，输入源块对应上面介绍的`本地磁盘文件或目录`、`HDFS 文件或目录`和`关系型数据库`，负责描述数据源的基本信息，比如数据在哪，是什么格式的，分隔符是什么等。顶点映射和边映射与该输入源绑定，可以选择输入源的哪些列，哪些列作为id、哪些作为属性，以及每一列映射成什么属性，列的值映射成属性的什么值等等。
顶点映射与边映射

2020-11-12 04:57 UTC, javeme commented on quickstart/hugegraph-loader.md
> +以最通俗的话讲，每一个映射块描述了：要导入的文件在哪，文件的每一行要作为哪一类顶点/边，文件的哪些列是需要的，以及这些列对应顶点/边的什么属性。
文件的哪些列是需要导入的

2020-11-12 04:57 UTC, javeme commented on quickstart/hugegraph-loader.md
> +这里直接给出上面图模型和数据文件的输入源的两个版本的映射文件
改进下以更加容易理解

2020-11-12 04:57 UTC, javeme commented on quickstart/hugegraph-loader.md
> +- id: 输入源的 id，该字段用于支持一些内部功能，非必填（会自动生成），但强烈建议写上，对于调试大有裨益；
未填时会自动生成

2020-11-12 04:57 UTC, javeme commented on quickstart/hugegraph-loader.md
> +--failure-mode      | false        |         | 是否使用失败模式，导入以前导入失败的那些记录
失败模式为 true 时，会导入之前失败了的数据。一般来说失败数据文件需要在人工更正编辑好后，再次进行导入。

2020-11-19 10:51 UTC, zhoney approved these changes

2020-11-20 03:24 UTC, javeme commented on quickstart/hugegraph-loader.md
> +```javascript
json

2020-11-20 03:24 UTC, javeme commented on quickstart/hugegraph-loader.md
> +1.0 版本的映射文件是以顶点和边为中心，设置输入源；而 2.0 版本是以输入源为中心，设置顶点和边映射。有些输入源（比如一个文件）既能生成顶点，也能生成边，如果用 1.0 版的格式写，就需要在 vertex 和 egde 映射块中各写一次 input 块，这两次的 input 块是完全一样的；而 2.0 版本只需要写一次 input。所以 2.0 版相比于 1.0 版，能省掉一些 input
为了减少误解可以使用 “映射文件 1.0 版本”

2020-11-20 03:45 UTC, javeme approved these changes

2020-11-20 10:05 UTC, zhoney approved these changes

2020-11-20 10:05 UTC, merged