add auth manager doc
hugegraph/hugegraph-doc pull request #63
Opened 2020-11-12 06:11 UTC by xuliguov5

2020-11-12 06:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hugegraph/hugegraph-doc?pullRequest=63) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hugegraph/hugegraph-doc?pullRequest=63) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hugegraph/hugegraph-doc?pullRequest=63) it.</sub>

2020-11-16 12:40 UTC, javeme commented on clients/restful-api/auth.md
> +包括UserAPI、AccessAPI、BelongAPI、GroupAPI、TargetAPI
add some overview description first

2020-11-16 12:40 UTC, javeme commented on clients/restful-api/auth.md
> +
remove empty lines

2020-11-16 12:40 UTC, javeme commented on clients/restful-api/auth.md
> +#### 9.1.1 创建target
change order to: User Group Target Belong Access, put POST/PUT/DELETE/GET together for each class.

2020-11-17 06:21 UTC, javeme requested changes

2020-11-17 06:21 UTC, javeme commented on clients/restful-api/auth.md
> +    "user_create": "2020-11-11 16:13:34.836"
调整一下参数顺序，user_password设置一个123456示例即可

2020-11-17 06:21 UTC, javeme commented on clients/restful-api/auth.md
> +- id:需要删除的用户 Id
冒号后面统一放置一个空格

2020-11-17 06:21 UTC, javeme commented on clients/restful-api/auth.md
> +    "user_phone": "123456"
改一个更像手机号的内容

2020-11-17 06:21 UTC, javeme commented on clients/restful-api/auth.md
> +返回结果会将修改过的全部内容都返回
返回结果是包含修改过的内容在内的整个用户组对象

2020-11-17 06:21 UTC, javeme commented on clients/restful-api/auth.md
> +资源配置：'person'的顶点，且城市属性是'Beijing'，年龄属性大于等于20。
类型是'person'的顶点

2020-11-17 06:21 UTC, javeme commented on clients/restful-api/auth.md
> +#### 9.4.1 关联角色(belong)API
使用中文括号

2020-11-17 06:21 UTC, javeme commented on clients/restful-api/auth.md
> +主要关联用户和用户组的关系，一个用户可以关联一个或者多个用户组。用户组拥有相关资源的权限，不同用户组的资源权限可以理解为不同的角色。即给用户关联角色。
去掉“主要”

2020-11-17 06:21 UTC, javeme commented on clients/restful-api/auth.md
> +#### 9.4.1 关联角色(belong)API
标号不合理，参考其它接口文档的框架结构

2020-11-17 09:37 UTC, javeme commented on clients/restful-api/auth.md
> +### 9.1 Auth
用户认证与权限控制

2020-11-17 09:37 UTC, javeme commented on clients/restful-api/auth.md
> +包括UserAPI、GroupAPI、TargetAPI、BelongAPI、AccessAPI
用户认证与权限控制接口包括5类：UserAPI、GroupAPI、TargetAPI、BelongAPI、AccessAPI

2020-11-17 09:37 UTC, javeme commented on clients/restful-api/auth.md
> +##### 权限管理：
可以去掉这个标题

2020-11-17 09:37 UTC, javeme commented on clients/restful-api/auth.md
> +包括：创建用户，删除用户，修改用户，和查询用户相关信息接口
“包括”之前加上主语

2020-11-17 09:37 UTC, javeme commented on clients/restful-api/auth.md
> +描述：用户boss拥有用户组all对资源graph1的读权限。
示例的含义是：用户'boss'拥有对'graph1'图中北京人的读权限。

2020-11-17 09:37 UTC, javeme commented on clients/restful-api/auth.md
> +包括UserAPI、GroupAPI、TargetAPI、BelongAPI、AccessAPI
移动到举例说明的后面

2020-11-17 09:37 UTC, javeme commented on clients/restful-api/auth.md
> +其中 user_name 和 user_password 为必填
在前面增加一个空行

2020-11-17 10:36 UTC, javeme submitted a review, later dismissed

2020-11-17 10:36 UTC, javeme commented on clients/restful-api/auth.md
> +修改了user_name、user_password和user_phone
修改了 => 修改

2020-11-17 13:40 UTC, zhoney requested changes

2020-11-17 13:40 UTC, zhoney commented on clients/restful-api/auth.md
> +#### 9.2 用户（User）API
```
###
```

2020-11-18 03:34 UTC, zhoney submitted a review, later dismissed

2020-11-18 05:59 UTC, javeme requested changes

2020-11-18 05:59 UTC, javeme commented on clients/restful-api/auth.md
> +target_resources资源配置列表：
先说明：“target_resources可以包括多个target_resource，每个target_resource包含：”

2020-11-18 05:59 UTC, javeme commented on clients/restful-api/auth.md
> +**如精细资源："target_resources": [{"type":"VERTEX","label":"person","properties":{"city":"Beijing","age":"P.gte(20)"}}]**
不需要加粗的

2020-11-18 05:59 UTC, javeme commented on clients/restful-api/auth.md
> +资源配置：类型是'person'的顶点，且城市属性是'Beijing'，年龄属性大于等于20。
资源配置含义

2020-11-18 05:59 UTC, javeme commented on clients/restful-api/auth.md
> +- target_resources: 资源配置(列表)
翻译为“资源定义”更具体

2020-11-18 05:59 UTC, javeme commented on clients/restful-api/auth.md
> +##### request body
统一大小写 Request Body

2020-11-18 05:59 UTC, javeme commented on clients/restful-api/auth.md
> +- limit:返回结果条数的上限
冒号后面加空格，全文检查下以免遗漏

2020-11-18 05:59 UTC, javeme commented on clients/restful-api/auth.md
> +修改type
修改资源定义中的type

2020-11-18 05:59 UTC, javeme commented on clients/restful-api/auth.md
> +赋权接口包括：赋权的创建、删除、修改和查询
统一加上句号

2020-11-18 11:57 UTC, zhoney submitted a review, later dismissed

2020-11-18 12:42 UTC, javeme approved these changes

2020-11-18 13:27 UTC, Linary approved these changes

2020-11-19 09:23 UTC, zhoney approved these changes

2020-11-19 09:24 UTC, merged