add hubble user guide doc
hugegraph/hugegraph-doc pull request #66
Opened 2020-11-19 08:56 UTC by Jerry098

2020-11-19 08:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hugegraph/hugegraph-doc?pullRequest=66) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hugegraph/hugegraph-doc?pullRequest=66) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hugegraph/hugegraph-doc?pullRequest=66) it.</sub>

2020-11-20 04:16 UTC, javeme requested changes

2020-11-20 04:16 UTC, javeme commented on quickstart/hugegraph-hubble.md
> +1.	可进行单条删除或批量删除操作。
“可进行单条删除或批量删除操作。”
-- 添加主语等信息减少上下文依赖

2020-11-20 04:16 UTC, javeme commented on quickstart/hugegraph-hubble.md
> +Gremlin查询后，下方为图结果展示区域，提供3种图结果展示方式，分别为：【图】、【表格】、【Json】模式。
【图模式】【表格模式】【Json模式】。

2020-11-20 04:16 UTC, javeme commented on quickstart/hugegraph-hubble.md
> +右击顶点，出现顶点的菜单入口，可进行展示、查询、隐藏等操作
增加一下“双击”的作用说明

2020-11-20 04:16 UTC, javeme commented on quickstart/hugegraph-hubble.md
> +-	隐藏：点击后，隐藏选中点及与之关联的边
统一下结尾的标点符号

2020-11-20 04:16 UTC, javeme commented on quickstart/hugegraph-hubble.md
> +##### 3.3.4	设置数据映射
本节格式乱了

2020-11-20 04:16 UTC, javeme commented on quickstart/hugegraph-hubble.md
> +1.	图区下方记载每次查询记录，包括：查询时间、执行类型、内容、状态、耗时、收藏、加载操作，实现图执行的全方位记录，有迹可循，并可对执行内容快读加载复用
包括：查询时间、执行类型、内容、状态、耗时，以及【收藏】和【加载】操作

2020-11-20 04:16 UTC, javeme commented on quickstart/hugegraph-hubble.md
> +1.	图区下方记载每次查询记录，包括：查询时间、执行类型、内容、状态、耗时、收藏、加载操作，实现图执行的全方位记录，有迹可循，并可对执行内容快读加载复用
“并可对执行内容快读加载复用”--感觉念不通

2020-11-20 04:16 UTC, javeme commented on quickstart/hugegraph-hubble.md
> +2.	提供语句的收藏功能，可对常用语句进行收藏操作，方便高频词快速调用
方便高频语句快速调用

2020-11-20 11:23 UTC, Linary requested changes

2020-11-20 11:23 UTC, Linary commented on SUMMARY.md
> +* [Visual graph analysis with HugeGraph-Hubble](quickstart/hugegraph-hubble.md)
make short

2020-11-20 11:29 UTC, Linary approved these changes

2020-11-20 11:29 UTC, javeme approved these changes

2020-11-20 11:30 UTC, merged