doc: update some doc description & menu
hugegraph/hugegraph-doc pull request #80
Opened 2021-05-24 09:59 UTC by imbajin

1. remove some outdated design conception
2. adjust `REST-API` &  Guide` position
3. add some default params for client
4. add some comments for `skip_degree`
5. add comment for Cassandra page
6. add auth-api request example & link page in rest-menu

2021-05-24 10:07 UTC, zhoney requested changes

2021-05-24 10:07 UTC, zhoney commented on config/config-authentication.md
> +Authorization: Basic admin 123456
use xxxxxx instead of 123456

2021-05-24 10:07 UTC, zhoney commented on clients/restful-api/traverser.md
> +	- skip_degree：用于设置查询过程中舍弃超级顶点的最小边数，即当某个顶点的邻接边数目大于 skip_degree 时，完全舍弃该顶点，选填项，默认为0 (关闭)，表示不跳过任何点 (注意:  开启此配置后，会无视 max_degree 参数优先确认当前点是否需要舍弃，并产生实际遍历开销，对查询性能影响可能有较大影响，请确认理解后再开启)
不要用“无视”。

开启此配置后，遍历时会尝试访问一个顶点的skip_degree条边，而不仅仅是max_degree条边，对查询性能.....

2021-05-24 11:44 UTC, zhoney submitted a review, later dismissed

2021-05-27 04:26 UTC, javeme commented on clients/hugegraph-api.md
> +- Graph Data
the "Data" word is too general, prefer to keep the origin title.

2021-05-27 04:26 UTC, javeme commented on clients/hugegraph-client.md
> +                                  .configTimeout(20) // 默认 20s
超时默认 20s

2021-05-27 04:26 UTC, javeme commented on clients/hugegraph-client.md
> +                                  .configUser("", "") // 默认未开启用户权限
"**", "**"

2021-05-27 04:26 UTC, javeme commented on clients/restful-api/edge.md
> +此时`"page": null`表示已经没有下一页了 (注: 后端为 Cassandra 时，为了优化性能，直接访问最后一条数据时 page 仍不会显示为 null，其他情况一致)
如果后端为 Cassandra ，当返回正好为最后一页时，page 可能并不为空，通过该 page 再次请求数据时会返回【空数据】及 【page=null】。本行为主要是基于性能考虑。

2021-05-27 04:26 UTC, javeme commented on clients/restful-api/traverser.md
> +	- skip_degree：用于设置查询过程中舍弃超级顶点的最小边数，即当某个顶点的邻接边数目大于 skip_degree 时，完全舍弃该顶点，选填项，默认为0 (关闭)，表示不跳过任何点 (注意:  开启此配置后，遍历时会尝试访问一个顶点的 skip_degree 条边，而不仅仅是 max_degree 条边，这样有额外的遍历开销，对查询性能影响可能有较大影响，请确认理解后再开启)
"(关闭)" => "(不启用)"

2021-05-27 04:26 UTC, javeme commented on clients/restful-api/traverser.md
> +	- skip_degree：用于设置查询过程中舍弃超级顶点的最小边数，即当某个顶点的邻接边数目大于 skip_degree 时，完全舍弃该顶点，选填项，默认为0 (关闭)，表示不跳过任何点 (注意:  开启此配置后，遍历时会尝试访问一个顶点的 skip_degree 条边，而不仅仅是 max_degree 条边，这样有额外的遍历开销，对查询性能影响可能有较大影响，请确认理解后再开启)
"选填项，" 后加上： ”如果开启时，要求满足 skip_degree >= max_degree 约束“

2021-05-27 04:26 UTC, javeme commented on clients/restful-api/traverser.md
> +	- skip_degree：用于设置查询过程中舍弃超级顶点的最小边数，即当某个顶点的邻接边数目大于 skip_degree 时，完全舍弃该顶点，选填项，默认为0 (关闭)，表示不跳过任何点 (注意:  开启此配置后，遍历时会尝试访问一个顶点的 skip_degree 条边，而不仅仅是 max_degree 条边，这样有额外的遍历开销，对查询性能影响可能有较大影响，请确认理解后再开启)
类似

2021-05-27 04:26 UTC, javeme commented on clients/restful-api/vertex.md
> +此时`"page": null`表示已经没有下一页了 (注: 后端为 Cassandra 时，为了优化性能，直接访问最后一条数据时 page 仍不会显示为 null，其他情况一致)
类似

2021-05-27 04:51 UTC, imbajin commented on clients/hugegraph-api.md
> +- Graph Data
seems `Graph` is also general?  maybe consider `Graph Elements` / `Graph Vertex & Edge` / `Graph Source Data` ?

2021-05-27 04:56 UTC, imbajin commented on clients/hugegraph-client.md
> +                                  .configUser("", "") // 默认未开启用户权限
seems there is no difference?

2021-05-27 09:18 UTC, javeme approved these changes

2021-05-31 02:51 UTC, Linary approved these changes

2021-06-01 04:36 UTC, merged